### PR TITLE
Resolves #159 - Replace all `template_tag` instances with `div`

### LINKED ISSUE #159: Replace all `template_tag` with `div`
Template tags are causing issues with connecting stimulus into the template tag. So it would be best to remove it.

### PR DESCRIPTION
**Pull request by AthiraKadampatta**
Resolves: #159

### CODE REVIEW

**Comment by SethHorsley** [comment]
awesome!! Thanks for the pr. Can you submit a pr with for the updated docs in the rbui-web repo too

**Comment by AthiraKadampatta** [comment]
Hi @SethHorsley I checked the rbui-web repo and did not find the need to update there. Please let me know if I am missing anything

**Comment by SethHorsley** [comment]
Oh ok i will check it out.

**Comment by SethHorsley** [comment]
just checked it and if you open the the alert dialog page the alert dialog is open by default now. Same thing for the command component. I just added some docs to the readme of this repo with some tips on contributing. Hope this helps. If you need more help just ask.

**Comment by SethHorsley** [comment]
we will probably have to break this down into a couple different pr's fixing the template tags

**Pull request closed without merging**
